[Model]
model_path = "path/to/model.tla"
# init = "Init"
# next = "Next"
# config_path = "path/to/module.cfg"
# invariants = ["Inv1", "Inv2"]
# examples = ["Ex1", "Ex2"]

[Constants]
# n = 42
# foo = "bar"

[Config]
traces_dir = "traces/"
