# A Makefile to build all audit artifacts

all: docker

docker:
	./setup.sh
	
atomkraft:
	# this package should be installed in the root directory of atomkraft
	python3 -m pip install atomkraft-informal
